#!/usr/bin/env bash

if [ $# -ge 2 ] && [[ ${@:$#} == *.s19 ]]; then
  stty 115200 -parenb cs8 -cstopb &&
  echo 'load' | tee ${@:1:$# - 1} 1> /dev/null 2> /dev/null &&
  sleep 1 &&
  cat ${@:$#} > $1 &&
  sleep 1 &&
  echo 'go' > $1
else
  echo 'Usage:   rtsend <conn> <s19>'
  echo 'Example: rtsend /dev/ttyUSB0 Debug/RTS-Lab.s19'
fi
